build:
  stage: build
  image: rbonifaz/wahay-rpm-build:latest
  before_script:
    - dnf install -y golang-github-sirupsen-logrus-devel
    - "eval $(ssh-agent -s)"
    - 'ssh-add <(echo "$FEDORA_PACKAGING_PRIVATE_KEY")'
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh
    - 'echo -e "[fedora.autonomia.digital]:4243,[185.108.78.22]:4243 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFE8IPu1LfB0ePyhgBFTyzXRNBZUiYa1ZaSnkFb746r3MgZQlfMhfxdMtrY3bKoiQ4i+HEUTCUN4BJ5n2PMdGz4=" > ~/.ssh/known_hosts'    
    - chmod 644 ~/.ssh/known_hosts
    - 'scp -r -P4243  fedora-repo@fedora.autonomia.digital:packages/upload/f31/golang*devel*.rpm .'
    - rpm -ivh golang*devel*.rpm

  script:
    - git clone https://github.com/digitalautonomy/wahay.git
    - cd wahay
    - git checkout 3906ea63d21872d25893e247322f0ee34d00a499
    - cd ..
    - mv wahay/ wahay-3906ea63d21872d25893e247322f0ee34d00a499
    - tar zcf wahay-3906ea63d21872d25893e247322f0ee34d00a499.tar.gz wahay-3906ea63d21872d25893e247322f0ee34d00a499 
    - mkdir f30 f31
    - fedpkg --release f30 local
    - 'find . -name "wahay*fc30*.rpm" -exec mv {} f30 \;'
    - fedpkg --release f31 local
    - 'find . -name "wahay*fc31*.rpm" -exec mv {} f31 \;'
    - 'scp -r -P4243 f30/* fedora-repo@fedora.autonomia.digital:packages/upload/f30'
    - 'scp -r -P4243 f31/* fedora-repo@fedora.autonomia.digital:packages/upload/f31'

  artifacts:
    paths:
      - 'f30/*.rpm'
      - 'f31/*.rpm'
