build:
  stage: build
  image: digitalautonomy/wahay:0.4-build-rpm
  before_script:
    - dnf install -y golang-github-sirupsen-logrus-devel golang-github-stretchr-testify-devel
    - "eval $(ssh-agent -s)"
    - 'ssh-add <(echo "$FEDORA_PACKAGING_PRIVATE_KEY")'
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh
    - 'echo -e "[fedora.autonomia.digital]:4243,[185.108.78.22]:4243 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFE8IPu1LfB0ePyhgBFTyzXRNBZUiYa1ZaSnkFb746r3MgZQlfMhfxdMtrY3bKoiQ4i+HEUTCUN4BJ5n2PMdGz4=" > ~/.ssh/known_hosts'
    - chmod 644 ~/.ssh/known_hosts
    - 'scp -r -P4243  fedora-repo@fedora.autonomia.digital:packages/upload/f38/golang*devel*.rpm .'
    - rpm -Uvh golang*devel*.rpm

  script:
    - git clone https://github.com/digitalautonomy/wahay.git wahay-87d0bcf5ea8b75df9f723ce0a8cf39ef45fd65e9
    - cd wahay-87d0bcf5ea8b75df9f723ce0a8cf39ef45fd65e9
    - git checkout 87d0bcf5ea8b75df9f723ce0a8cf39ef45fd65e9
    - cd ..
    - tar zcf wahay-87d0bcf5ea8b75df9f723ce0a8cf39ef45fd65e9.tar.gz wahay-87d0bcf5ea8b75df9f723ce0a8cf39ef45fd65e9
    - ./build_all.sh f30 f31 f32 f33 f34 f35 f36 f37 f38
