# Generated by go2rpm 1
%bcond_without check

# https://github.com/digitalautonomy/wahay
%global goipath         github.com/digitalautonomy/wahay
%global commit          4abfed1038dca7b0553ae04ff69ebb804d939e74

%gometa

%global common_description %{expand:
An easy-to-use, secure and decentralized conference call application (this
repository is a mirror of an internal work repository).}

%global golicenses      COPYING LICENSE
%global godocs          DEVELOPER.md CONTRIBUTORS README.md\\\
                        deployment/supported-bundle-distros.txt\\\
                        deployment/supported-packages-distros.txt\\\
                        .gitlab/issue_templates/Story.md doc

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        An easy-to-use, secure and decentralized conference call application (this repository is a mirror of an internal work repository)

License:        GPL-3.0-only
# FIXME: Upstream uses unknown SPDX tag GPL-3.0-only!
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/atotto/clipboard)
BuildRequires:  golang(github.com/coyim/gotk3adapter/gdka)
BuildRequires:  golang(github.com/coyim/gotk3adapter/gdki)
BuildRequires:  golang(github.com/coyim/gotk3adapter/gliba)
BuildRequires:  golang(github.com/coyim/gotk3adapter/glibi)
BuildRequires:  golang(github.com/coyim/gotk3adapter/gtka)
BuildRequires:  golang(github.com/coyim/gotk3adapter/gtki)
BuildRequires:  golang(github.com/cubiest/jibberjabber)
BuildRequires:  golang(github.com/digitalautonomy/grumble/pkg/logtarget)
BuildRequires:  golang(github.com/digitalautonomy/grumble/server)
BuildRequires:  golang(github.com/kardianos/osext)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/wybiral/torgo)
BuildRequires:  golang(golang.org/x/crypto/scrypt)
BuildRequires:  golang(golang.org/x/net/proxy)
BuildRequires:  golang(golang.org/x/text/language)
BuildRequires:  golang(golang.org/x/text/message)
BuildRequires:  golang(golang.org/x/text/message/catalog)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/coyim/gotk3adapter/glib_mock)
BuildRequires:  golang(github.com/coyim/gotk3adapter/gtk_mock)
BuildRequires:  golang(gopkg.in/check.v1)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/wahay %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYING LICENSE
%doc DEVELOPER.md CONTRIBUTORS README.md deployment/supported-bundle-distros.txt
%doc deployment/supported-packages-distros.txt .gitlab/issue_templates/Story.md
%doc doc
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Mar 16 13:19:24 -05 2020 rafael <rafael@autonomia.digital> - 0-0.1.20200316git4abfed1
- Initial package

